export const RECEIVE_ADDRES = 'receive_addres'
export const RECEIVE_CATEGORYS = 'receive_categorys'
export const RECEIVE_SHOPS = 'receive_shops'
export const RECEIVE_USER = 'receive_user'
export const RECEIVE_TOKEN = 'receive_token'
export const LOGOUT = 'logout'
